$(document).ready(function(){var lastDecoded='';var lastEncoded='';var processDecode=function(){if($('#encoded-savegame').val()==lastDecoded){return;}
lastDecoded=$('#encoded-savegame').val();$.ajax({type:'POST',url:'decode.php',data:{savegame:$('#encoded-savegame').val()},success:function(data){$('#decoded-savegame').val(data);ga('send','event','convert encoded','success',{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','convert encoded','success']);_paq.push(['trackGoal',2]);},error:function(data){ga('send','event','convert encoded',data.responseText,{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','convert encoded',data.responseText]);}});};var processEncode=function(){if($('#decoded-savegame').val()==lastEncoded){return;}
lastEncoded=$('#decoded-savegame').val();$.ajax({type:'POST',url:'encode.php',data:{savegame:$('#decoded-savegame').val()},success:function(data){$('#encoded-savegame').val(data);ga('send','event','convert decoded','success',{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','convert decoded','success']);_paq.push(['trackGoal',3]);},error:function(data){ga('send','event','convert decoded',data.responseText,{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','convert decoded',data.responseText]);}});};var changeTimeout=null;$("#encoded-savegame").on('change keyup paste',function(){if(changeTimeout!=null){clearTimeout(changeTimeout);}
changeTimeout=setTimeout(processDecode,1000);});$("#decoded-savegame").on('change keyup paste',function(){if(changeTimeout!=null){clearTimeout(changeTimeout);}
changeTimeout=setTimeout(processEncode,1000);});var currentPage=0;var showPage=function(action){action=action||false;var pages=$('.page');pages.hide();$(pages[currentPage]).show();if(currentPage==0){$('#prevButton').css('opacity','0.4');}else{$('#prevButton').css('opacity','1');}
if(currentPage==pages.length- 1){$('#nextButton').css('opacity','0.4');}else{$('#nextButton').css('opacity','1');}
document.location.hash='page-'+ currentPage;if(action!=false){ga('send','event','navbutton',action,{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','navbutton',document.location.pathname+'#page-'+ currentPage]);}};showPage();$('#prevButton').click(function(){if(currentPage==0){return;}
currentPage--;showPage('previous');});$('#nextButton').click(function(){if(currentPage==$('.page').length- 1){return;}
currentPage++;showPage('next');if(currentPage==6){requestGoldFunction();}});var requestGoldFunction=function(){var epicHeroes=$('.epicHero');var epicHeroUpgrades={};for(var i in epicHeroes){var input=$(epicHeroes[i]);var levels=parseInt(input.val());if(levels!=0&&!isNaN(levels)){epicHeroUpgrades[input.data('id')]=levels;}
if(input.data('id')==35){break;}}
$.ajax({type:'POST',url:'sg.php',data:{savegame:$('#savegame').val(),resetCooldowns:$('#resetCooldowns').prop('checked'),resetGuilded:$('#resetGuilded').prop('checked'),resetPrimal:$('#resetPrimal').prop('checked'),gold:$('#gold').val()+ $('#goldMultiplier').val(),critChance:$('#critChance').val(),critMultiplier:$('#critMultiplier').val(),heroSouls:$('#heroSouls').val(),freeRespecs:$('#freeRespecs').val(),epicHeroUpgrades:epicHeroUpgrades,unlockAncients:$('#unlockAncients').prop('checked'),infiniteClickstorm:$('#infiniteClickstorm').prop('checked'),infinitePowersurge:$('#infinitePowersurge').prop('checked'),infiniteLuckyStrikes:$('#infiniteLuckyStrikes').prop('checked'),infiniteMetalDetector:$('#infiniteMetalDetector').prop('checked'),infiniteGoldenClicks:$('#infiniteGoldenClicks').prop('checked'),infiniteSuperClicks:$('#infiniteSuperClicks').prop('checked'),achievements:achievements,},success:function(data){$('#your-new-savegame').val(data);$('#your-new-savegame').select();ga('send','event','submit savegame','success',{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','submit savegame','success']);_paq.push(['trackGoal',1]);},error:function(data){currentPage-=3;showPage();ga('send','event','submit savegame',data.responseText,{'page':document.location.pathname+'#page-'+ currentPage});_paq.push(['trackEvent','submit savegame',data.responseText]);alert(data.responseText);}});};$('#requestGold').click(requestGoldFunction);var achievements={};$('.achievement').click(function(){var achievementID=$(this).data('id');if(achievements[achievementID]===undefined){achievements[achievementID]=true;$(this).css('border-color','#0F0');}else if(achievements[achievementID]===true){achievements[achievementID]=false;$(this).css('border-color','#F00');}else{delete achievements[achievementID];$(this).css('border-color','#FFF');}});var sendRating=function(rating){$.ajax({type:'POST',url:'rating.php',data:{rating:rating},success:function(data){_paq.push(['trackEvent','rating',rating]);_paq.push(['trackGoal',4]);ga('send','event','rating',rating);alert('Rating successfully stored!');},error:function(data){alert('Failed to store rating; please try again later!');}});};$('#like').click(function(){sendRating(1);return false;});$('#dislike').click(function(){sendRating(0);return false;});});
